services:
    database:
        image: mysql/mysql-server:8.0
        restart: always

        ports:
            - 3306:3306

        environment:
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
