### categories index
GET http://localhost:8000/api/categories
Accept: application/json

### category show
GET http://localhost:8000/api/categories/2
Accept: application/json

### categories show
POST http://localhost:8000/api/categories
Accept: application/json
Content-Type: application/json

{
    "name": "Category 1"
}

### categories update
PUT http://localhost:8000/api/categories/2
Accept: application/json
Content-Type: application/json

{
    "name": "Category 2"
}

### categories delete
DELETE http://localhost:8000/api/categories/2
