### categories index
GET http://localhost:8000/api/categories
Accept: application/json

### category show
GET http://localhost:8000/api/categories/2
Accept: application/json

### categories show
POST http://localhost:8000/api/categories
Accept: application/json
Content-Type: application/json

{
    "name": "Category 1"
}

### categories update
PUT http://localhost:8000/api/categories/2
Accept: application/json
Content-Type: application/json

{
    "name": "Category 2"
}

### categories delete
DELETE http://localhost:8000/api/categories/2

### products index
GET http://localhost:8000/api/products
Accept: application/json

### products index pagination
GET http://localhost:8000/api/products?page=1
Accept: application/json

### products index filter category
GET http://localhost:8000/api/products?category_id=2
Accept: application/json

### products index filter category
GET http://localhost:8000/api/products?active=1
Accept: application/json

### products show
GET http://localhost:8000/api/products/2
Accept: application/json

### products create
POST http://localhost:8000/api/products
Accept: application/json
Content-Type: application/json

{
    "name": "Name Foo",
    "stock": 1,
    "price": 10.5,
    "active": true,
    "category_id": 1
}

### products update
PUT http://localhost:8000/api/products/1
Accept: application/json
Content-Type: application/json

{
    "name": "Name 6",
    "stock": 12,
    "price": 10.60,
    "active": true,
    "category_id": 1
}

### products delete
DELETE http://localhost:8000/api/products/2
Accept: application/json

### images store
POST http://localhost:8000/api/products/2/images
Accept: application/json
Content-Type: application/json

{
    "image": "https://picsum.photos/400/400?t=ab"
}

### images delete
DELETE http://localhost:8000/api/products/2/images/2
Accept: application/json
